### ISSUE TITLE
Remove packrat

### ISSUE THREAD

**Issue by annahprice** [Health-SocialCare-Scotland/r-project-structure#2]
Unfortunately I think we need to remove packrat from these templates. I say unfortunately because it's not really ideal not to have some kind of package management in place, but we really haven't found it useful at all. Can folks assigned let me know if you agree and if so I'll remove it? Thanks :smile:

**Comment by jvillacampa** [comment]
I haven't used packrat at all, so I'll leave this one to you guys

**Comment by alan-y** [comment]
I haven't really used it either for any proper piece of work. I think package management would be good but to me, it's only needed for vital pieces of work (not much falls under this category). Other stuff can always be fixed up with a little bit of effort by reworking your code. By the way, dplyr 0.8 which will be released in January on CRAN is likely to cause some breaking changes if you ever group by factor variables. So in that case you'll need to rework your code 😄

**Comment by jackhannah95** [comment]
Yeah I think get rid of it. So far it's been a bigger pain than having no package management.

**Comment by davidc92** [comment]
I vote to get rid too. It just doesn't really work.

**Comment by annahprice** [comment]
Thanks all, I will delete. I would disagree @alan-y - I think it's important for code that will be used for anything, other than really experimental work. The more widespread R use is, the more we will run into problems which stem from people having different package versions (either from each other or from their past selves). On a large scale this will result in an unnecessary loss of time fixing these problems, and be a generally irritating system for analysts to work with. I think it's fine to remove packrat and not have anything for now, but it needs to be raised as an ongoing issue with R.

**Comment by alan-y** [comment]
I think a huge amount of work is exploratory or things done as a bit of a one-off so doing package management each time for stuff like this would be overkill. I have lots of scripts that I now really only keep for reference. The main area where its needed is for anything that is made into a 'production' or where reproducibility is really important.

Anyway it seems that we need something better than packrat to come along...

**Comment by annahprice** [comment]
Perhaps it's different between HPS and ISD as I think that most coding done in ISD is for publications or work for customers, which I would count as production code. Anyway, I have removed packrat!

**Comment by alan-y** [comment]
I think you're right - I suppose one big difference is that HPS has a lot less data management support so lots of exploratory work has to be done to figure out things as you go along. Also in BBV/STI team, its not always possible to release stuff and a lot is management info only. Happy you've reached a concensus haha :smile:
